FROM php:8.3-cli
RUN apt-get update && apt-get install -y \
    git unzip libpq-dev zlib1g-dev libzip-dev \
    libonig-dev curl
RUN docker-php-ext-install pdo pdo_pgsql pcntl
WORKDIR /var/www/html
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
COPY . .
RUN composer install --no-interaction --prefer-dist --optimize-autoloader
EXPOSE 8000
CMD php artisan serve --host=0.0.0.0 --port=8000
